'use strict';

//fetch song
export const FETCH_SONG = "FETCH_SONG";
export const FETCH_SONG_SUCCESS = "FETCH_SONG_SUCCESS";
export const FETCH_SONG_FAILURE = "FETCH_SONG_FAILURE";
export const FETCH_MORE_SONG_SUCCESS = "FETCH_MORE_SONG_SUCCESS";
export const FETCH_MORE_SONG_FAILURE = "FETCH_MORE_SONG_FAILURE";
export const IS_PLAY_SONG_REQUEST = "IS_PLAY_SONG_REQUEST";
