'use strict';

export const CLIENT_ID = 'a281614d7f34dc30b665dfcaa3ed7505';
export const FETCH_SONG = "FETCH_SONG";
export const FETCH_SONG_SUCCESS = "FETCH_SONG_SUCCESS";
export const FETCH_SONG_FAILURE = "FETCH_SONG_FAILURE";
export const FETCH_MORE_SONG_SUCCESS = "FETCH_MORE_SONG_SUCCESS";
export const FETCH_MORE_SONG_FAILURE = "FETCH_MORE_SONG_FAILURE";
export const IS_PLAY_SONG_REQUEST = "IS_PLAY_SONG_REQUEST";
export const ON_LOAD_START = "ON_LOAD_START";
export const ON_LOADED_METADATA = "ON_LOADED_METADATA";
export const ON_PAUSE = "ON_PAUSE";
export const ON_PLAY = "ON_PLAY";
export const ON_TIME_UPDATE = "ON_TIME_UPDATE";
export const ON_VOLUME_CHANGE = "ON_VOLUME_CHANGE";
export const PLAY_SONG = "PLAY_SONG";
export const TOGGLE_REPEAT = "TOGGLE_REPEAT";
export const TOGGLE_SHUFFLE = "TOGGLE_SHUFFLE";
