'use strict';

export const CLIENT_ID = 'a281614d7f34dc30b665dfcaa3ed7505';
//fetch song
export const FETCH_SONG = "FETCH_SONG";
export const FETCH_SONG_SUCCESS = "FETCH_SONG_SUCCESS";
export const FETCH_SONG_FAILURE = "FETCH_SONG_FAILURE";
export const FETCH_MORE_SONG_SUCCESS = "FETCH_MORE_SONG_SUCCESS";
export const FETCH_MORE_SONG_FAILURE = "FETCH_MORE_SONG_FAILURE";
export const IS_PLAY_SONG_REQUEST = "IS_PLAY_SONG_REQUEST";
